[package]
name = "core-model-builder"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
codemap.workspace = true
serde.workspace = true
codemap-diagnostic.workspace = true
thiserror.workspace = true

core-model = { path = "../core-model" }
core-plugin-shared = { path = "../core-plugin-shared" }

[dev-dependencies]

[lib]
doctest = false
