[package]
name = "core-model-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
codemap.workspace = true
serde.workspace = true
codemap-diagnostic.workspace = true
thiserror.workspace = true

core-model = { path = "../core-model" }
core-plugin-shared = { path = "../core-plugin-shared" }

[dev-dependencies]

[lib]
