[package]
name = "postgres-core-resolver"
version.workspace = true
edition.workspace = true
publish = false

[features]
network = [
    "exo-sql/tls",
    "exo-sql/postgres-url",
    "exo-sql/testing",
    "exo-sql/pool",
]
bigdecimal = ["exo-sql/bigdecimal"]

[dependencies]
thiserror.workspace = true
tokio-postgres = { workspace = true, default-features = false }
tracing.workspace = true

exo-sql = { path = "../../../libs/exo-sql" }
exo-env = { path = "../../../libs/exo-env" }
common = { path = "../../common" }

[dev-dependencies]
tokio.workspace = true
builder = { path = "../../builder" }
core-resolver = { path = "../../core-subsystem/core-resolver", features = [
    "test-context",
] }
graphql-router = { path = "../../graphql-router" }
postgres-model-builder = { path = "../postgres-model-builder" }
http.workspace = true
wasm-bindgen-test.workspace = true

[lib]
crate-type = ["lib"]
doctest = false
