[package]
name = "deno-resolver-dynamic"
version = "0.1.0"
edition = "2021"

[dependencies]
core-plugin-interface = { path = "../../core-subsystem/core-plugin-interface" }
deno-resolver = { path = "../deno-resolver" }

[dev-dependencies]

[lib]
crate-type = ["cdylib"]
