[package]
name = "subsystem-model-util"
version = "0.1.0"
edition = "2021"

[dependencies]
typed-generational-arena = { version = "0.2", features = ["serde"] }
serde = "1.0"
async-graphql-parser = "4.0.5"
async-graphql-value = "4.0.5"

core-model = { path = "../../core-subsystem/core-model" }
core-plugin = { path = "../../core-subsystem/core-plugin" }

[dev-dependencies]



[lib]
