[package]
name = "subsystem-model-util"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
typed-generational-arena.workspace = true
serde.workspace = true
async-graphql-parser.workspace = true

core-model = { path = "../../core-subsystem/core-model" }
core-plugin-shared = { path = "../../core-subsystem/core-plugin-shared" }

[dev-dependencies]


[lib]
doctest = false
