[package]
name = "subsystem-model-util"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
typed-generational-arena.workspace = true
serde.workspace = true
async-graphql-parser.workspace = true
async-graphql-value.workspace = true

core-model = { path = "../../core-subsystem/core-model" }
core-plugin-shared = { path = "../../core-subsystem/core-plugin-shared" }

[dev-dependencies]


[lib]
