kind: pipeline
name: default

trigger:
  branch:
  - main

steps:
  - name: discord-start
    image: appleboy/drone-discord
    pull: if-not-exists
    settings:
      webhook_id: "926191813780459520"
      webhook_token: "i2MeZ0VMXm1oVH8sC6HD6GBS6L-UEUyOxr16Dv3kCLVyknE4FiiNSy5R-hKaQYUxfMYB"
      message: "Build {{build.number}} started {{build.link}}"
  - name: rustfmt-clippy
    image: payas-ci-image
    pull: if-not-exists
    depends_on:
      - discord-start
    volumes:
    - name: sccache
      path: /sccache
    commands:
      - cargo fmt --all -- --check
      - cargo clippy --all --all-targets --all-features -- -D warnings

  - name: test
    image: payas-ci-image
    pull: if-not-exists
    depends_on:
      - discord-start
    volumes:
    - name: sccache
      path: /sccache
    commands:
      - cargo build --release # TODO: figure out how to build cdylibs during tests implicitly
      - CLAY_TEST_DATABASE_URL=postgresql://postgres@database:5432 cargo test --workspace

  - name: test-integration
    image: payas-ci-image
    pull: if-not-exists
    depends_on:
      - discord-start
    volumes:
    - name: sccache
      path: /sccache
    commands:
      - (cd graphiql && npm install && npm run prod-build)
      - cargo build --release
      - export PATH=./target/release:$PATH
      - CLAY_TEST_DATABASE_URL=postgresql://postgres@database:5432 clay test --run-introspection-tests integration-tests

  - name: discord-end
    image: appleboy/drone-discord
    pull: if-not-exists
    depends_on:
      - rustfmt-clippy
      - test
      - test-integration
    when:
      status: [success, failure]
    settings:
      webhook_id: "926191813780459520"
      webhook_token: "i2MeZ0VMXm1oVH8sC6HD6GBS6L-UEUyOxr16Dv3kCLVyknE4FiiNSy5R-hKaQYUxfMYB"
      message: >
        {{#success build.status}}
          Build {{build.number}} succeeded.
          Changes: {{commit.message}}. 
        {{else}}
          Build {{build.number}} failed.
          Changes: {{commit.message}}.
          See: {{build.link}}
        {{/success}}

services:
  - name: database
    image: postgres:12-buster
    command: ["postgres", "-c", "max_connections=1000"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: test
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
- name: sccache
  host:
    path: /home/ci/sccache
