kind: pipeline
name: default

trigger:
  branch:
  - main

steps:
  - name: slack-start
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      username: drone
      channel: ci
      template: Build {{build.number}} started {{build.link}}

  - name: rustfmt-clippy
    image: rust:buster
    pull: if-not-exists
    depends_on:
      - slack-start
    commands:
      - curl -fsSL https://deb.nodesource.com/setup_16.x | bash - && apt-get install -y nodejs
      - rustup component add rustfmt
      - rustup component add clippy
      - cargo install --rev v0.19.5 --git https://github.com/tree-sitter/tree-sitter.git tree-sitter-cli
      - cargo fmt --all -- --check
      - cargo clippy --all-targets --all-features -- -D warnings

  - name: test
    image: rust:buster
    pull: if-not-exists
    depends_on:
      - slack-start
    commands:
      - curl -fsSL https://deb.nodesource.com/setup_16.x | bash - && apt-get install -y nodejs
      - cargo install --rev v0.19.5 --git https://github.com/tree-sitter/tree-sitter.git tree-sitter-cli
      - cargo test

  - name: test-integration
    image: rust:buster
    pull: if-not-exists
    depends_on:
      - slack-start
    commands:
      - curl -fsSL https://deb.nodesource.com/setup_16.x | bash - && apt-get install -y nodejs
      - cargo install --rev v0.19.5 --git https://github.com/tree-sitter/tree-sitter.git tree-sitter-cli
      - CLAY_USE_CARGO=1 CLAY_TEST_DATABASE_URL=postgresql://postgres@database:5432 cargo run --bin clay test integration-tests

  - name: slack-end
    image: plugins/slack
    depends_on:
      - rustfmt-clippy
      - test
      - test-integration
    when:
      status: [success, failure]
    settings:
      webhook: https://hooks.slack.com/services/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
      username: drone
      channel: ci

services:
  - name: database
    image: postgres:12-buster
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: test
      POSTGRES_HOST_AUTH_METHOD: trust
