kind: pipeline
name: default

trigger:
  branch:
  - main

steps:
  - name: slack-start
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      username: drone
      channel: ci
      template: Build {{build.number}} started {{build.link}}

  - name: rustfmt-clippy
    image: payas-ci-image
    pull: if-not-exists
    depends_on:
      - slack-start
    volumes:
    - name: sccache
      path: /sccache
    commands:
      - cargo fmt --all -- --check
      - cargo clippy --all-targets --all-features -- -D warnings

  - name: test
    image: payas-ci-image
    pull: if-not-exists
    depends_on:
      - slack-start
    volumes:
    - name: sccache
      path: /sccache
    commands:
      - CLAY_TEST_DATABASE_URL=postgresql://postgres@database:5432 cargo test --test '*'

  - name: test-integration
    image: payas-ci-image
    pull: if-not-exists
    depends_on:
      - slack-start
    volumes:
    - name: sccache
      path: /sccache
    commands:
      - cargo build --release
      - export PATH=./target/release:$PATH
      - CLAY_TEST_DATABASE_URL=postgresql://postgres@database:5432 clay test integration-tests

  - name: slack-end
    image: plugins/slack
    depends_on:
      - rustfmt-clippy
      - test
      - test-integration
    when:
      status: [success, failure]
    settings:
      webhook: https://hooks.slack.com/services/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
      username: drone
      channel: ci

services:
  - name: database
    image: postgres:12-buster
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: test
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
- name: sccache
  host:
    path: /home/ci/sccache
