# Must be kept in sync with deny.toml
accepted = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "Artistic-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "MIT",
    "MPL-2.0",
    "OpenSSL",
    "Unicode-DFS-2016",
    "Zlib",
]
private = { ignore = true }
workarounds = ["ring"]

[webpki]
accepted = ["ISC", "BSD-3-Clause", "NOASSERTION"]

[rustls-webpki]
accepted = ["ISC", "BSD-3-Clause", "NOASSERTION"]
