[package]
name = "payas-wasm-model-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
payas-core-model = { path = "../../payas-core-plugin/payas-core-model" }
payas-core-model-builder = { path = "../../payas-core-plugin/payas-core-model-builder" }

payas-wasm-model = { path = "../payas-wasm-model" }
payas-plugin-model-builder-util = { path = "../../payas-plugin-util/payas-plugin-model-builder-util" }

[dev-dependencies]



[lib]
