FROM ghcr.io/exograph/cli:latest as builder

WORKDIR /app

COPY ./src ./src

RUN exo build

FROM ghcr.io/exograph/cli-server:latest

WORKDIR /app

COPY --from=builder /app/target/index.exo_ir ./target/index.exo_ir

CMD ["exo-server"]
