operation: |
    mutation {
        # C1 has A1, A2, A3
        # C2 has A1, A3
        # A4 is not in any concert
        A1: createArtist(data: {name: "A1"}) {
            id @bind(name: "A1_id")
        }
        A2: createArtist(data: {name: "A2"}) {
            id @bind(name: "A2_id")
        }
        A3: createArtist(data: {name: "A3"}) {
            id @bind(name: "A3_id")
        }
        A4: createArtist(data: {name: "A4"}) {
            id @bind(name: "A4_id")
        }
        c1: createConcert(data: {title: "C1", concertArtists: [
            {artist: {id: 1}, rank: 1, role: "main"},
            {artist: {id: 2}, rank: 2, role: "main"}, 
            {artist: {id: 3}, rank: 3, role: "accompanying"}
        ]}) {
            id @bind(name: "c1_id")
        }
        # c2 doesn't have artist: {id: 2}
        c2: createConcert(data: {title: "C2", concertArtists: [
            {artist: {id: 1}, rank: 1, role: "main"},
            {artist: {id: 3}, rank: 3, role: "accompanying"}
        ]}) {
            id @bind(name: "c2_id")
        }

        c1_notification_1: createNotification(data: {concert: {id: 1}, title: "C1 Notification 1", message: "C1 Notification 1 Message"}) {
            id @bind(name: "c1_notification_1_id")
        }
        c1_notification_2: createNotification(data: {concert: {id: 1}, title: "C1 Notification 2", message: "C1 Notification 2 Message"}) {
            id @bind(name: "c1_notification_2_id")
        }
        c2_notification_1: createNotification(data: {concert: {id: 2}, title: "C2 Notification 1", message: "C2 Notification 1 Message"}) {
            id @bind(name: "c2_notification_1_id")
        }
        c2_notification_2: createNotification(data: {concert: {id: 2}, title: "C2 Notification 2", message: "C2 Notification 2 Message"}) {
            id @bind(name: "c2_notification_2_id")
        }
        plain_notification: createNotification(data: {title: "Plain Notification", message: "Plain Notification Message"}) {
            id @bind(name: "plain_notification_id")
        }                           
    }  
