[package]
name = "deno-builder-dynamic"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
core-plugin-interface = { path = "../../core-subsystem/core-plugin-interface" }
deno-builder = { path = "../deno-builder" }

[dev-dependencies]

[lib]
crate-type = ["cdylib"]
doctest = false
