[package]
name = "wasm-graphql-resolver"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
async-graphql-parser.workspace = true
async-trait.workspace = true
thiserror.workspace = true
wasmtime.workspace = true

exo-wasm = { path = "../../../libs/exo-wasm" }
core-plugin-interface = { path = "../../core-subsystem/core-plugin-interface" }
common = { path = "../../common" }
wasm-graphql-model = { path = "../wasm-graphql-model" }


[dev-dependencies]

[lib]
crate-type = ["lib"]
doctest = false
