[package]
name = "wasm-resolver-dynamic"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql-parser.workspace = true
async-graphql-value.workspace = true
async-recursion.workspace = true
async-trait.workspace = true
futures.workspace = true
serde_json = { workspace = true, features = ["preserve_order"] }
thiserror.workspace = true
wasmtime.workspace = true
wasmtime-wasi.workspace = true

exo-wasm = { path = "../../../libs/exo-wasm" }
core-plugin-interface = { path = "../../core-subsystem/core-plugin-interface" }
wasm-model = { path = "../wasm-model" }


[dev-dependencies]


[lib]
crate-type = ["cdylib"]
