[package]
name = "wasm-resolver-dynamic"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
core-plugin-interface = { path = "../../core-subsystem/core-plugin-interface" }
wasm-resolver = { path = "../wasm-resolver" }

[dev-dependencies]

[lib]
crate-type = ["cdylib"]
