[package]
name = "payas-deno-model"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql-parser = "4.0.5"
async-graphql-value = "4.0.5"
serde = { version = "1.0.136", features = ["derive"] }
bincode = "1.3.3"

payas-subsystem-model-util = { path = "../../payas-subsystem-util/payas-subsystem-model-util" }
payas-core-model = { path = "../../payas-core-subsystem/payas-core-model" }
payas-core-plugin = { path = "../../payas-core-subsystem/payas-core-plugin" }

[dev-dependencies]



[lib]
