[package]
name = "postgres-rest-builder"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
postgres-core-model = { path = "../postgres-core-model" }
postgres-rest-model = { path = "../postgres-rest-model" }
postgres-core-builder = { path = "../postgres-core-builder" }
core-plugin-shared = { path = "../../core-subsystem/core-plugin-shared" }
core-model-builder = { path = "../../core-subsystem/core-model-builder" }

[dev-dependencies]

[lib]
doctest = false
