[package]
name = "payas-introspection-resolver"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-graphql-parser = "4.0.5"
async-graphql-value = "4.0.5"
async-recursion = "1.0.0"
async-trait = "0.1.53"
futures = "0.3"
maybe-owned = "0.3.4"
serde_json = { version = "1.0", features = ["preserve_order"] }
thiserror = "1.0.30"
tokio = "1"

payas-core-resolver = { path = "../../payas-core-plugin/payas-core-resolver" }
payas-core-model = { path = "../../payas-core-plugin/payas-core-model" }


[dev-dependencies]

[lib]
