operation: |
    mutation {
        mobydick: createBook(data: {
            name: "Moby-Dick",
            published_on: "1851-10-18",
            modified_time: "2021-07-06T20:08:47.1234567-07:00",
            modified_time_stripped: "2021-07-06T20:08:47",
            reading_club_time: "14:00:00"
        }) {
            id
        }

        nineteeneightyfour: createBook(data: {
            name: "Nineteen Eighty-Four"
            published_on: "1949-06-08",
            modified_time: "2021-07-12T22:58:16+00:00",
            modified_time_stripped: "2021-07-12T22:58:16",
            reading_club_time: "09:00:00"
        }) {
            id
        }

        cookbook: createBook(data: {
            name: "Gordon Ramsay's Ultimate Cookery Course"
            published_on: "2012-08-30",
            modified_time: "2021-07-16T20:00:00+00:00",
            modified_time_stripped: "2021-07-16T20:00:00",
            reading_club_time: "09:00:00"
        }) {
            id
        }
    } 
