operation: |
    mutation {
        createBook(data: {
            id: 1,
            published_on: "2018-04-17",
            modified_time: "2021-07-06T20:08:47.1234567-07:00",
            modified_time_stripped: "2021-07-06T20:08:47",
            reading_club_time: "14:00:00.02"
        }) {
            id
        }
    } 
