# We must use "debian:bookworm*" (and not "debian:buster") as the base runtime image to match the libc version used while building the binaries

## Create a builder image with exograph release binaries
FROM debian:bookworm-slim as builder

RUN apt-get update && apt-get -y install unzip

WORKDIR /usr/src
COPY exograph-x86_64-unknown-linux-gnu.zip ./exograph-x86_64-unknown-linux-gnu.zip
RUN unzip ./exograph-x86_64-unknown-linux-gnu.zip


## Build the runtime image with just the binaries we need
FROM postgres:bookworm

### Install ca-certificates and tzdata (needed to establish TLS connections and set the timezone)
RUN apt-get update \
  && apt-get install -y ca-certificates tzdata \
  && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/src/exo /usr/local/bin/exo
COPY --from=builder /usr/src/exo-server /usr/local/bin/exo-server

ENV TZ=Etc/UTC
ENV APP_USER=exo
ENV APP_DIR=/usr/src/app

### Create a non-root user to run the binaries
RUN groupadd $APP_USER \
  && useradd -g $APP_USER $APP_USER \
  && mkdir -p ${APP_DIR}
RUN chown -R $APP_USER:$APP_USER ${APP_DIR}
USER $APP_USER

### Set the host for exo-server to 0.0.0.0 so it can bind to all interfaces (and the host can connect)
ENV EXO_SERVER_HOST=0.0.0.0

WORKDIR ${APP_DIR}
