# Runtime setup for systems based on apt-get
RUN apt-get update \
  && apt-get install -y ca-certificates tzdata \
  && rm -rf /var/lib/apt/lists/*
RUN groupadd $APP_USER \
  && useradd -g $APP_USER $APP_USER \
  && mkdir -p ${APP}
RUN chown -R $APP_USER:$APP_USER ${APP}
USER $APP_USER