# Build setup for Amazon Linux 2023 

# Install NodeJS (needed by tree-sitter and to build the GraphiQL app)
RUN curl -sL https://rpm.nodesource.com/setup_16.x | bash -
RUN yum install -y file gcc make nodejs openssl-devel zlib-devel 

# Need to install Rust manually (not through yum, which is a bit older version 
# and since it doesn't install rustup, it doesn't respect rust-toolchain.toml settings)
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH="/root/.cargo/bin:$PATH"