[package]
name = "deno-graphql-builder"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
core-model = { path = "../../core-subsystem/core-model" }
core-model-builder = { path = "../../core-subsystem/core-model-builder" }
subsystem-model-builder-util = { path = "../../subsystem-util/subsystem-model-builder-util" }
deno-graphql-model = { path = "../deno-graphql-model" }
exo-deno = { path = "../../../libs/exo-deno" }
common = { path = "../../common" }

url.workspace = true
deno_core.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
codemap = "0.1.3"

[lib]
crate-type = ["lib"]
doctest = false
