operation: |
    mutation(
        $username: String!, 
        $primaryEmailId: String!,
        $secondaryEmailId: String!
        $emailDomain: String!,
        $initial_event_rsvp: String!
        $initial_internal_event_rsvp: String!
    ) {
        createUser(data: {
            username: $username,
            primaryEmailId: $primaryEmailId,
            secondaryEmailId: $secondaryEmailId,
            emailDomain: $emailDomain,
            rsvps: [
                { event: $initial_event_rsvp }
            ],
            internalRsvps: [
                { event: $initial_internal_event_rsvp }
            ]
        }) {
            id @bind(name: "alice_user_id")
            rsvps {
                id @bind(name: "alice_rsvp_id")
            }
            internalRsvps {
                id @bind(name: "alice_internal_rsvp_id")
            }
        }
    }
variable: |
    {
        "username": "Alice02",
        "primaryEmailId": "alice",
        "secondaryEmailId": "alice2",
        "emailDomain": "example.com",
        "initial_event_rsvp": "Concert1",
        "initial_internal_event_rsvp": "InternalConcert1"
    }