[package]
name = "core-model"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
serde.workspace = true
typed-generational-arena.workspace = true
async-graphql-parser.workspace = true
async-graphql-value.workspace = true

[dev-dependencies]

[lib]
doctest = false
