[package]
name = "core-model"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
typed-generational-arena = { version = "0.2", features = ["serde"] }
async-graphql-parser.workspace = true
async-graphql-value.workspace = true

[dev-dependencies]

[lib]
