[package]
name = "core-model"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde.workspace = true
typed-generational-arena.workspace = true
async-graphql-parser.workspace = true
async-graphql-value.workspace = true

[dev-dependencies]

[lib]
doctest = false
