[package]
name = "deno-model"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql-parser = "4.0.5"
async-graphql-value = "4.0.5"
serde = { version = "1.0.136", features = ["derive"] }
bincode = "1.3.3"

subsystem-model-util = { path = "../../subsystem-util/subsystem-model-util" }
core-model = { path = "../../core-subsystem/core-model" }
core-plugin-shared = { path = "../../core-subsystem/core-plugin-shared" }

[dev-dependencies]



[lib]
