[package]
name = "deno-model-builder-dynamic"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
core-plugin-interface = { path = "../../core-subsystem/core-plugin-interface" }
deno-model-builder = { path = "../deno-model-builder" }

[dev-dependencies]

[lib]
crate-type = ["cdylib"]
doctest = false
