operation: |
    mutation($username: String!, $email_id: String!, $email_domain: String!) {
        createUser(data: {
            username: $username,
            email_id: $email_id,
            email_domain: $email_domain
        })
    }
variable: |
    {
        "username": "Alice02",

        // alice@example.com
        "email_id": "alice",
        "email_domain": "example.com",
    }