[package]
name = "wasm-graphql-resolver-dynamic"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
core-plugin-interface = { path = "../../core-subsystem/core-plugin-interface" }
wasm-graphql-resolver = { path = "../wasm-graphql-resolver" }

[dev-dependencies]

[lib]
crate-type = ["cdylib"]
doctest = false
