[package]
name = "postgres-model"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
typed-generational-arena.workspace = true
serde.workspace = true
bincode.workspace = true
async-graphql-parser.workspace = true
async-graphql-value.workspace = true
anyhow.workspace = true

exo-sql = { path = "../../../libs/exo-sql" }
core-plugin-interface = { path = "../../core-subsystem/core-plugin-interface" }

[dev-dependencies]
tokio.workspace = true
wasm-bindgen-test.workspace = true
stripmargin = "0.1.1"

builder = { path = "../../builder" }
postgres-model-builder = { path = "../postgres-model-builder" }

[lib]
doctest = false
