[package]
name = "postgres-model"
version = "0.1.0"
edition = "2021"

[dependencies]
typed-generational-arena = { version = "0.2", features = ["serde"] }
serde = "1.0"
async-graphql-parser = "5.0.6"
async-graphql-value = "5.0.6"
bincode = "1.3.3"

payas-sql = { path = "../../../libs/payas-sql" }
core-plugin-interface = { path = "../../core-subsystem/core-plugin-interface" }

[dev-dependencies]


[lib]
