[package]
name = "postgres-model"
version = "0.1.0"
edition = "2021"

[dependencies]
typed-generational-arena.workspace = true
serde.workspace = true
bincode.workspace = true
async-graphql-parser.workspace = true
async-graphql-value.workspace = true

payas-sql = { path = "../../../libs/payas-sql" }
core-plugin-interface = { path = "../../core-subsystem/core-plugin-interface" }

[dev-dependencies]


[lib]
