[package]
name = "postgres-graphql-resolver-dynamic"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
core-plugin-interface = { path = "../../core-subsystem/core-plugin-interface" }
postgres-graphql-resolver = { path = "../postgres-graphql-resolver", features = [
  "network",
  "bigdecimal",
] }

[dev-dependencies]

[lib]
crate-type = ["cdylib"]
doctest = false
