[package]
name = "wasm-builder"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
core-plugin-shared = { path = "../../core-subsystem/core-plugin-shared" }
core-plugin-interface = { path = "../../core-subsystem/core-plugin-interface" }
core-model-builder = { path = "../../core-subsystem/core-model-builder" }
wasm-graphql-builder = { path = "../wasm-graphql-builder" }

[dev-dependencies]


[lib]
crate-type = ["lib"]
doctest = false
