# See https://github.com/rust-lang/cargo/issues/5034#issuecomment-1050225208
# and the comment before that (if we were to restrict the target only to clippy,
# caches for clippy and normal build will clobber each other).
[target.'cfg(all())']
rustflags = ["-Dclippy::wildcard_imports"]

# Configure getrandom for wasm32 targets
[target.wasm32-unknown-unknown]
rustflags = ["--cfg", "getrandom_backend=\"wasm_js\""]

# Windows configuration with static CRT linking.
# Use rust-lld (LLVM linker) instead of MSVC's link.exe to avoid PDB complexity
# errors (LNK1318) when linking the exo-deno-snapshot build script with hundreds
# of dependencies. rust-lld ships with Rust and handles large builds better.
[target.x86_64-pc-windows-msvc]
rustflags = [
  "-C",
  "target-feature=+crt-static",
  "-C",
  "link-arg=/subsystem:console",
  "-C",
  "linker=rust-lld",
]

[target.'cfg(all(windows, debug_assertions))']
rustflags = [
  "-C",
  "target-feature=+crt-static",
  "-C",
  "link-arg=/STACK:4194304",
  "-C",
  "linker=rust-lld",
]
