operation: |
    query($id:Int!) {
        venue(id:2) { # Use alias. Needed anyway, but also tests for how we process aliases
            id
            name
            published
        }
    } 
variable: |
    {
        "id": 1
    }
auth: |
    {
        "sub": 2,
        "role": "ROLE_USER"
    }