operation: |
    mutation {
        e1: createExample(data: { limit: 1, age: 20 }) {
              id
              limit
              age
        }
        e2: createSthElse(data: { limit: 1337, age: 20 }) {
              id
              limit
              age
        }
    }
