operation: |
    mutation {
        e1: createNumbers(data: { limit: 1, age: 20, float_limit: 1.1, price: 30.0 }) {
              id
              limit
              age
              float_limit
              price
        }
    }
