[package]
name = "payas-core-model-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
codemap = "0.1.3"
serde = { version = "1.0.136", features = ["derive"] }
codemap-diagnostic = "0.1.1"


payas-model = { path = "../../payas-model" }

[dev-dependencies]



[lib]
