[package]
name = "payas-subsystem-model-builder-util"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
codemap = "0.1.3"
codemap-diagnostic = "0.1.1"
typed-generational-arena = { version = "0.2", features = ["serde"] }
thiserror = "1.0.30"

payas-core-model = { path = "../../payas-core-subsystem/payas-core-model" }
payas-core-plugin = { path = "../../payas-core-subsystem/payas-core-plugin" }
payas-core-model-builder = { path = "../../payas-core-subsystem/payas-core-model-builder" }
payas-subsystem-model-util = { path = "../payas-subsystem-model-util" }

[dev-dependencies]



[lib]
