// Copyright Exograph, Inc. All rights reserved.
//
// Use of this software is governed by the Business Source License
// included in the LICENSE file at the root of this repository.
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0.

//! Types to represent the operations that are generated by the postgres subsystem builder.
//!
//! Queries and mutations stem from the types defined inside each Postgres module (such as `type Todo { ... }`).
//!
//! Consider a postgres module with the following types:
//! ```exo
//! @postgres
//! module TodoModule {
//!    type Todo {
//!       @pk id: Int = autoIncrement()
//!       title: String
//!       completed: Boolean
//!    }
//! }
//! ```
//!
//! Queries like `todos`, `todo`, and `todoAgg` as well as mutations like `createTodo`, `updateTodo`, and `deleteTodo` will be
//! generated by the postgres subsystem builder.

use std::fmt::Debug;

use async_graphql_parser::types::Type;
use core_plugin_interface::core_model::type_normalization::{Operation, Parameter};
use core_plugin_interface::core_model::types::OperationReturnType;

use serde::{Deserialize, Serialize};

use crate::types::EntityType;

/// An operation such as a query or mutation.
///
/// * `P` - This parameter allows differentiating between, for example,
///   [`PkQuery`](`super::query::PkQuery`), [`AggregateQuery`](super::query::AggregateQuery), and
///   [`PostgresMutation`](super::mutation::PostgresMutation).
#[derive(Serialize, Deserialize, Debug)]
pub struct PostgresOperation<P: OperationParameters> {
    /// The name of the operation such as `todos`, `todosAgg`, createTodo`, `updateTodo`, or `deleteTodo`.
    pub name: String,
    /// The parameters (if multiple parameters are needed, they are wrapped in a struct)
    pub parameters: P,
    /// The return type such as `Todo` or `[Todo]`.
    pub return_type: OperationReturnType<EntityType>,
}

/// Supports introspection of operation parameters
pub trait OperationParameters {
    /// Create an introspection version of the parameters
    fn introspect(&self) -> Vec<&dyn Parameter>;
}

impl<P: OperationParameters> Operation for PostgresOperation<P> {
    fn name(&self) -> &String {
        &self.name
    }

    fn parameters(&self) -> Vec<&dyn Parameter> {
        self.parameters.introspect()
    }

    fn return_type(&self) -> Type {
        (&self.return_type).into()
    }
}
