[package]
name = "wasm-model-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"

core-model = { path = "../../core-subsystem/core-model" }
core-plugin = { path = "../../core-subsystem/core-plugin" }
core-model-builder = { path = "../../core-subsystem/core-model-builder" }

wasm-model = { path = "../wasm-model" }
subsystem-model-builder-util = { path = "../../subsystem-util/subsystem-model-builder-util" }

[dev-dependencies]



[lib]
