[package]
name = "wasm-model-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
core-model = { path = "../../core-subsystem/core-model" }
core-plugin-shared = { path = "../../core-subsystem/core-plugin-shared" }
core-plugin-interface = { path = "../../core-subsystem/core-plugin-interface" }
core-model-builder = { path = "../../core-subsystem/core-model-builder" }

wasm-model = { path = "../wasm-model" }
subsystem-model-builder-util = { path = "../../subsystem-util/subsystem-model-builder-util" }

[dev-dependencies]


[lib]
crate-type = ["cdylib"]
