[package]
name = "wasm-model-builder"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
core-plugin-interface = { path = "../../core-subsystem/core-plugin-interface" }
wasm-model = { path = "../wasm-model" }
subsystem-model-builder-util = { path = "../../subsystem-util/subsystem-model-builder-util" }

[dev-dependencies]


[lib]
crate-type = ["cdylib"]
