operation: |
  fragment allTodoFields on Todo {
    id @bind(name: "id")
    title
    metadata {
      expectedEffortHrs
      notes
      completionDate
      tags
    }
    info {
      description
    }
  }
  mutation($groceriesTitle: String!, $groceriesMetadata: Metadata!, $groceriesInfo: Info,
           $cleanTitle: String!, $cleanMetadata: Metadata!, $cleanInfo: Info,
           $medicationTitle: String!, $medicationMetadata: Metadata!, $medicationInfo: Info) {
    groceries: createTodo(data: {
      title: $groceriesTitle
      metadata: $groceriesMetadata
      info: $groceriesInfo
    }) {
      id @bind(name: "groceriesId")
      ...allTodoFields
    }

    clean: createTodo(data: {
      title: $cleanTitle
      metadata: $cleanMetadata
      info: $cleanInfo
    }) {
      id @bind(name: "cleanId")
      ...allTodoFields
    }

    medication: createTodo(data: {
      title: $medicationTitle
      metadata: $medicationMetadata
      info: $medicationInfo
    }) {
      id @bind(name: "medicationId")
      ...allTodoFields
    }
  }
variable: |
  {
    "groceriesTitle": "Buy groceries",
    "groceriesMetadata": {
        "expectedEffortHrs": 1,
        "notes": "Buy apples, oranges, and milk",
        "completionDate": "2024-10-01",
        "tags": ["groceries", "shopping"]
    },
    "groceriesInfo": {
      "description": "Need to prepare for the party"
    },

    "cleanTitle": "Clean room",
    "cleanMetadata": {
      "expectedEffortHrs": 2,
      "notes": "Clean the room",
      "completionDate": "2024-10-02",
      "tags": []
    },
    "cleanInfo": {
      "description": "Guests are coming over"
    },

    "medicationTitle": "Refill medication",
    "medicationMetadata": {
      "notes": "Refill the medication",
      "completionDate": "2024-10-06",
      "tags": ["medication", "health"]
    },
    "medicationInfo": null
  }
