[package]
name = "deno-graphql-resolver-dynamic"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
core-plugin-interface = { path = "../../core-subsystem/core-plugin-interface" }
deno-graphql-resolver = { path = "../deno-graphql-resolver" }

[lib]
crate-type = ["cdylib"]
doctest = false
