pub const EXO_INTROSPECTION: &str = "EXO_INTROSPECTION";
pub const EXO_INTROSPECTION_LIVE_UPDATE: &str = "EXO_INTROSPECTION_LIVE_UPDATE";

pub const EXO_CORS_DOMAINS: &str = "EXO_CORS_DOMAINS";

pub const EXO_JWT_SECRET: &str = "EXO_JWT_SECRET";
pub const EXO_JWKS_ENDPOINT: &str = "EXO_JWKS_ENDPOINT";

pub const EXO_POSTGRES_URL: &str = "EXO_POSTGRES_URL";
pub const EXO_POSTGRES_USER: &str = "EXO_POSTGRES_USER";
pub const EXO_POSTGRES_PASSWORD: &str = "EXO_POSTGRES_PASSWORD";
pub const EXO_CONNECTION_POOL_SIZE: &str = "EXO_CONNECTION_POOL_SIZE";
pub const EXO_CHECK_CONNECTION_ON_STARTUP: &str = "EXO_CHECK_CONNECTION_ON_STARTUP";

pub const EXO_SERVER_PORT: &str = "EXO_SERVER_PORT";
