operation: |
    mutation {
        A1: createArtist(data: {name: "A1"}) {
            id
        }
        A2: createArtist(data: {name: "A2"}) {
            id
        }
        A3: createArtist(data: {name: "A3"}) {
            id
        }
        A4: createArtist(data: {name: "A4"}) {
            id
        }
        A5: createArtist(data: {name: "A5"}) {
            id
        }
        A6: createArtist(data: {name: "A6"}) {   
            id
        }     
        createConcert(data: {title: "C1", concertArtists: [
            {artist: {id: 1}, rank: 1, role: "main"},
            {artist: {id: 2}, rank: 2, role: "main"}, 
            {artist: {id: 3}, rank: 3, role: "accompanying"}
        ]}) {
            id
            title
            mainArtists: concertArtists(where: {role: {eq: "main"}}) {
                id
            }
            accArtists: concertArtists(where: {role: {eq: "accompanying"}}) {
                id
            }
        }                  
    }  
