[package]
name = "wasm-resolver"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
async-graphql-parser.workspace = true
async-recursion.workspace = true
async-trait.workspace = true
futures.workspace = true
serde_json = { workspace = true, features = ["preserve_order"] }
thiserror.workspace = true
wasmtime.workspace = true
wasmtime-wasi.workspace = true

exo-env = { path = "../../../libs/exo-env" }
exo-wasm = { path = "../../../libs/exo-wasm" }
core-plugin-interface = { path = "../../core-subsystem/core-plugin-interface" }
wasm-model = { path = "../wasm-model" }


[dev-dependencies]


[lib]
crate-type = ["lib"]
doctest = false
