[package]
name = "wasm-resolver"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql-parser = "4.0.5"
async-graphql-value = "4.0.5"
async-recursion = "1.0.0"
async-trait = "0.1.53"
futures = "0.3"
serde_json = { version = "1.0", features = ["preserve_order"] }
thiserror = "1.0.30"
wasmtime = "2.0.0"
wasmtime-wasi = "2.0.0"

payas-wasm = { path = "../../../libs/payas-wasm" }
core-plugin-interface = { path = "../../core-subsystem/core-plugin-interface" }
wasm-model = { path = "../wasm-model" }


[dev-dependencies]


[lib]
crate-type = ["cdylib"]
