[package]
name = "wasm-model"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql-parser = "4.0.5"
async-graphql-value = "4.0.5"
serde = { version = "1.0.136", features = ["derive"] }
bincode = "1.3.3"

subsystem-model-util = { path = "../../subsystem-util/subsystem-model-util" }
core-plugin-interface = { path = "../../core-subsystem/core-plugin-interface" }

[dev-dependencies]


[lib]
