name: Label PRs

on:
  pull_request_target:
    types: [opened, edited, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/conventional-release-labels@v1
        with:
          type_labels: >
            {
              "feat": "feat",
              "fix": "fix",
              "docs": "docs",
              "style": "style",
              "refactor": "refactor",
              "perf": "perf",
              "test": "test",
              "build": "build",
              "ci": "ci",
              "revert": "revert",
              "security": "security",
              "breaking": "breaking",
              "chore": "chore"
            }
          ignored_types: '["release"]'