[package]
name = "wasm-graphql-model-builder-dynamic"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
core-plugin-interface = { path = "../../core-subsystem/core-plugin-interface" }
wasm-graphql-model-builder = { path = "../wasm-graphql-model-builder" }

[dev-dependencies]

[lib]
crate-type = ["cdylib"]
doctest = false
